import { Copy, Send, Square } from "lucide-react";
import { ReactNode, useState } from "react";
import { PageHeader } from "../components/common/PageHeader";
import { StatusBadge } from "../components/common/StatusBadge";

export function Chat() {
  const [messages, setMessages] = useState(["Orchestrator: The compliance agent is waiting for approval on the data minimization recommendation.", "Human: Approve with a note to exclude sensitive employee fields."]);
  const [draft, setDraft] = useState("");
  const send = () => { if (!draft.trim()) return; setMessages([...messages, `Human: ${draft}`, "Agent: Recorded. The workflow can resume with the supplied approval note."]); setDraft(""); };
  return <div><PageHeader title="Workflow Chat" description="Human-agent interaction workspace for active workflow sessions." /><div className="grid gap-5 xl:grid-cols-[280px_1fr_320px]"><aside className="surface p-5"><h2 className="font-bold text-navy">Sessions</h2>{["Unified Dashboard", "Smart Loan", "Retail Signals"].map((item, i) => <button key={item} className={`mt-3 w-full rounded-lg border p-3 text-left text-sm ${i === 0 ? "border-electric bg-blue-50 text-enterprise" : "border-border bg-white"}`}>{item}<span className="block text-xs text-muted">Active workflow</span></button>)}</aside><section className="surface flex min-h-[620px] flex-col p-5"><h2 className="font-bold text-navy">Conversation History</h2><div className="mt-4 flex-1 space-y-3 overflow-auto">{messages.map((message, index) => <div key={`${message}-${index}`} className={`rounded-xl p-4 text-sm leading-6 ${message.startsWith("Human") ? "ml-auto max-w-[80%] bg-enterprise text-white" : "mr-auto max-w-[80%] bg-page text-text"}`}>{message}<button className="ml-2 align-middle opacity-70" aria-label="Copy message"><Copy size={14} /></button></div>)}</div><div className="mt-4 flex gap-2"><input className="input" placeholder="Send message or approval note" value={draft} onChange={(e) => setDraft(e.target.value)} onKeyDown={(e) => e.key === "Enter" && send()} /><button className="btn btn-primary" onClick={send}><Send size={16} />Send</button><button className="btn btn-secondary"><Square size={16} />Stop</button></div></section><aside className="surface p-5"><h2 className="font-bold text-navy">Active Agent</h2><p className="mt-2 text-sm text-muted">Ethical and Compliance Agent</p><div className="mt-4 space-y-3"><Info label="Workflow Status" value={<StatusBadge value="Human Input Required" />} /><Info label="Execution Progress" value="5 of 6 agents" /><Info label="Current Task" value="Review security, compliance, privacy, and ethical risks." /></div><button className="btn btn-primary mt-5 w-full">Resume Workflow</button><button className="btn btn-secondary mt-3 w-full">View Execution Details</button></aside></div></div>;
}
function Info({ label, value }: { label: string; value: ReactNode }) { return <div className="rounded-lg border border-border bg-page p-3"><b className="text-xs text-muted">{label}</b><div className="mt-2 text-sm font-semibold text-navy">{value}</div></div>; }
