import { useMemo, useState } from "react";
import { ReactNode } from "react";
import { Activity, Bot, CheckCircle, Clock, XCircle } from "lucide-react";
import { PageHeader } from "../components/common/PageHeader";
import { MetricCard } from "../components/common/MetricCard";
import { BarMetricChart, SuccessPie, TrendChart } from "../components/common/Charts";
import { StatusBadge } from "../components/common/StatusBadge";
import { telemetry, workflows } from "../data/mockData";

export function Observability() {
  const [workflow, setWorkflow] = useState("All");
  const filtered = useMemo(() => workflow === "All" ? telemetry : telemetry.map((p) => ({ ...p, executions: Math.round((p.executions ?? 0) * 0.62), success: Math.round((p.success ?? 0) * 0.62), failed: Math.max(1, Math.round((p.failed ?? 0) * 0.62)) })), [workflow]);
  const totals = filtered.reduce((acc, p) => ({ executions: acc.executions + (p.executions ?? 0), success: acc.success + (p.success ?? 0), failed: acc.failed + (p.failed ?? 0), tokens: acc.tokens + (p.tokens ?? 0) }), { executions: 0, success: 0, failed: 0, tokens: 0 });
  return <div><PageHeader title="AI Observability" description="Mock telemetry updates based on selected filters." /><Filters workflow={workflow} setWorkflow={setWorkflow} /><div className="grid gap-4 md:grid-cols-3 xl:grid-cols-6"><MetricCard label="Total Agent Executions" value={totals.executions} icon={Activity} /><MetricCard label="Successful Executions" value={totals.success} icon={CheckCircle} /><MetricCard label="Failed Executions" value={totals.failed} icon={XCircle} /><MetricCard label="Average Latency" value="854ms" icon={Clock} /><MetricCard label="Token Consumption" value={totals.tokens.toLocaleString()} /><MetricCard label="Active Workflows" value={workflows.length} icon={Bot} /></div><div className="mt-5 grid gap-5 xl:grid-cols-2"><Chart title="Agent Execution Trends"><TrendChart data={filtered} /></Chart><Chart title="Success vs Failure"><SuccessPie success={totals.success} failed={totals.failed} /></Chart><Chart title="Average Response Latency"><TrendChart data={filtered} dataKey="latency" /></Chart><Chart title="Token Consumption Over Time"><BarMetricChart data={filtered} dataKey="tokens" /></Chart></div><div className="surface mt-5 overflow-auto p-5"><h2 className="mb-4 font-bold text-navy">Execution Log</h2><table className="w-full min-w-[760px] text-left text-sm"><thead className="text-muted"><tr>{["Execution ID","Workflow","Agent","Status","Duration","Tokens","Timestamp"].map((h) => <th key={h} className="border-b border-border p-3">{h}</th>)}</tr></thead><tbody>{workflows.flatMap((w) => w.agents.slice(0, 2).map((a, i) => <tr key={`${w.id}-${a.id}`}><td className="p-3">EX-{w.id}-{i}</td><td className="p-3">{w.name}</td><td className="p-3">{a.name}</td><td className="p-3"><StatusBadge value={i ? "Completed" : "Running"} /></td><td className="p-3">{42 + i * 8}s</td><td className="p-3">{(1800 + i * 450).toLocaleString()}</td><td className="p-3">2026-10-09 10:{20 + i}</td></tr>))}</tbody></table></div></div>;
}
function Filters({ workflow, setWorkflow }: { workflow: string; setWorkflow: (value: string) => void }) { return <div className="surface mb-5 grid gap-3 p-4 md:grid-cols-4"><select className="input"><option>Last 7 days</option><option>Last 30 days</option></select><select className="input" value={workflow} onChange={(e) => setWorkflow(e.target.value)}><option>All</option>{workflows.map((w) => <option key={w.id}>{w.name}</option>)}</select><select className="input"><option>All Agents</option><option>Compliance</option></select><select className="input"><option>All Statuses</option><option>Completed</option><option>Failed</option></select></div>; }
function Chart({ title, children }: { title: string; children: ReactNode }) { return <div className="surface p-5"><h2 className="mb-4 font-bold text-navy">{title}</h2>{children}</div>; }
